server_id: 377946908783673344 # your server id
darkmode: true # dark mode or not
title: "GWAFF V2"
bottom_message: "\n\nJoin cremes server for dedicated gwaff channel\nCheck out the github on bwac2517/gwaff"
plot:
  range: 60 # how many users to include in the plots
  minium_xp: 300 # anyone with a xp gain below this will not be included in the plots
  rank_range: 20 # the interval it starts a new graph
bar:
  range: 15 # how many users to include in the bar graph
versus:
  - 298294667219435521
  - 387259938977742849
  - 477148794861912084
  - 724378805728313395
  - 348848278365929473
  - 440802296159535109
data:
  range: 500
